name: VPM

on:
  push:
    branches:
      - develop

jobs:
  jre:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java: [ 8.0.252, 11.0.7, 13.0.3, 14.0.1 ]
    env:
      VPM_VERSION: veriblock-pop-miner-0.4.9-dev.174
    steps:
      - uses: actions/setup-java@v1
        name: set java version to ${{ matrix.java }}
        with:
          java-version: ${{ matrix.java }}
          java-package: jre
      - name: Test VPM
        run: |
          wget -q https://mirror.veriblock.org/${VPM_VERSION}.zip
          unzip -qq ${VPM_VERSION}.zip
          cd ${VPM_VERSION}/bin/
          (sleep 5; echo y; sleep 2; echo y; sleep 180; echo quit) | ./veriblock-pop-miner
