name: VPM

on:
  push:
    branches:
      - develop

jobs:
  jre:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java: [ 8.46.0.19, 11.39.15, 12.1.3, 13.31.11, 14.28.21 ]
    env:
      VPM_VERSION: veriblock-pop-miner-0.4.9-dev.174
    steps:
      - uses: actions/setup-java@v1
        name: set java version to ${{ matrix.java }}
        with:
          java-version: ${{ matrix.java }}
          java-package: jre
      - name: Test VPM
        run: |
          wget https://mirror.veriblock.org/${VPM_VERSION}.zip
          unzip ${VPM_VERSION}.zip
          cd ${VPM_VERSION}/bin/
          (sleep 5; echo y; sleep 2; echo y; sleep 180; echo quit) | ./veriblock-pop-miner
